"""empty message

Revision ID: 36e162f979b0
Revises: 9b4327cf283c
Create Date: 2024-12-11 03:45:39.697964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36e162f979b0'
down_revision = '9b4327cf283c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_constraint('uq_channel_category_name', type_='unique')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('idx_message_parent_id')
        batch_op.drop_constraint('message_parent_id_fkey', type_='foreignkey')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('thread_count')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presence_state', sa.String(length=20), nullable=True))
        batch_op.alter_column('preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('contact_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('contact_info',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('presence_state')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('message_parent_id_fkey', 'message', ['parent_id'], ['id'])
        batch_op.create_index('idx_message_parent_id', ['parent_id'], unique=False)

    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_channel_category_name', ['category_id', 'name'])

    # ### end Alembic commands ###
