"""empty message

Revision ID: de20893e2368
Revises: 70c94da19415
Create Date: 2024-12-11 15:30:52.671577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de20893e2368'
down_revision = '70c94da19415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('voice_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('voice_duration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reactions', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, 'channel', ['channel_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('status_emoji', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('presence_details', sa.JSON(), nullable=True))
        batch_op.alter_column('warning_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('warning_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('presence_details')
        batch_op.drop_column('status_emoji')
        batch_op.drop_column('banner')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reactions')
        batch_op.drop_column('voice_duration')
        batch_op.drop_column('voice_url')
        batch_op.drop_column('channel_id')

    # ### end Alembic commands ###
