"""Add profile connection columns

Revision ID: fc951057dc70
Revises: 06229ee22c51
Create Date: 2024-12-11 19:11:20.674357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc951057dc70'
down_revision = '06229ee22c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('github_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('spotify_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('spotify_display_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discord_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discord_username', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['discord_id'])
        batch_op.create_unique_constraint(None, ['github_id'])
        batch_op.create_unique_constraint(None, ['spotify_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('discord_username')
        batch_op.drop_column('discord_id')
        batch_op.drop_column('spotify_display_name')
        batch_op.drop_column('spotify_id')
        batch_op.drop_column('github_username')
        batch_op.drop_column('github_id')

    # ### end Alembic commands ###
